### ISSUE TITLE
A tut on delpoying the bot?

### ISSUE THREAD

**Issue by Yamac-Koc** [ArielYat/Whatsapp-bot-Project#35]
hey sir, i wonder if u can make a tut on yt or even write it down in the readme doc. It will help alot!
Thanks!!
![th](https://github.com/ArielYat/Whatsapp-bot-Project/assets/65724558/f96818f1-e5df-444a-a614-a5f019f9c919)

**Comment by Yamac-Koc** [comment]
@ArielYat @TheBooker66 @tomershush sorry for the disturbance

**Comment by TheBooker66** [comment]
Hey man, sure, I'll write a short tutorial in the readme a bit later

**Comment by TheBooker66** [comment]
@Yamac-Koc I updated the [readme](README.md) (and forgot to ping you). Is the explanation to your satisfaction? If it is, please close the issue. If it isn't, ping me back. I won't be available for the next week, but after it I can provide assistance.

**Comment by Yamac-Koc** [comment]
with the library now deceased. how do i upload my bot then? 
Sorry for the disturbance @TheBooker66

**Comment by TheBooker66** [comment]
You don't "upload" your bot anywhere. The library is deprecated and does not receive updates, but you can still download the latest version with npm and use your bot. It just won't get updates and will break over time.

**Comment by Yamac-Koc** [comment]
> You don't "upload" your bot anywhere. The library is deprecated and does not receive updates, but you can still download the latest version with npm and use your bot. It just won't get updates and will break over time.

ok sir. i wonder about how i will be able to attach my number to the bot?? i really dont understand that part... 

@TheBooker66

**Comment by TheBooker66** [comment]
I see the confusion - you attach your phone number to the bot in the terminal (or chromium window) after you start the process (with `npm run start`) by scanning a QR code. You should only need to do it once and then the session will save on your computer. I'll note that this process was not coded by us but by the library creator, so if you encounter a bug please ask him for advice.
